name: GitHub pages

on:
  push:
    branches:
      - main
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run : npm install

      - name: Generate Docs
        run : npm run docs

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_PUBLISH_ISO_8583 }}
          publish_dir: ./docs